# Usa la imagen base de PHP con Apache
FROM php:7.4-apache

# Copia los archivos de tu aplicación al directorio de Apache
COPY . /var/www/html/

# Expone el puerto 80
EXPOSE 80

# El comando para iniciar Apache ya está incluido en la imagen base